---
- name: Déploiement complet d'un serveur Minecraft Forge
  hosts: localhost
  become: yes
  become_method: sudo
  vars_prompt:
    - name: "server_ip"
      prompt: "Quelle adresse IP souhaitez-vous utiliser pour le fichier hosts ?"
      private: no
    - name: "project_path"
      prompt: "Chemin absolu où est situé votre répertoire SAE5.02 (se termine par /SAE5.02/) ?"
      private: no
      default: "~/SAE5.02"
  tasks:
    # Normalisation du chemin du projet
    - name: Expander le chemin utilisateur (~) dans project_path
      set_fact:
        project_path_expanded: "{{ project_path | expanduser }}"

    # Création de l'arborescence
    - name: Création des répertoires pour Ansible, Docker et leur contenu
      file:
        path: "{{ project_path_expanded }}/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - 'ansible/playbooks'
        - 'ansible/roles'
        - 'ansible/inventory'
        - 'docker/configs'
        - 'docker/mods'
        - 'docker/worlds'

    # Création du fichier d'inventaire pour Ansible
    - name: Création du fichier d'inventaire pour Ansible
      copy:
        content: |
          [serveur_ubuntu]
          {{ server_ip }} ansible_ssh_user=joris ansible_ssh_pass=Sterling7mc ansible_become_pass=Sterling7mc

          [minecraft_server]
          {{ server_ip }} ansible_ssh_user=joris ansible_ssh_pass=Sterling7mc ansible_become_pass=Sterling7mc
        dest: "{{ project_path_expanded }}/ansible/inventory/hosts"
        mode: '0644'

    # Créer le fichier install_docker.yml avant de l'inclure
    - name: Créer le fichier install_docker.yml
      copy:
        content: |
          ---
          - name: Installation de Docker et Docker Compose
            hosts: all
            become: yes
            tasks:
              - name: Mise à jour des paquets
                apt:
                  update_cache: yes

              - name: Installation des dépendances
                apt:
                  name:
                    - apt-transport-https
                    - ca-certificates
                    - curl
                    - software-properties-common
                  state: present

              - name: Ajout de la clé GPG Docker
                become: yes
                shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

              - name: Ajout du repository Docker
                apt_repository:
                  repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

              - name: Installation de Docker et Docker Compose
                apt:
                  name:
                    - docker-ce
                    - docker-ce-cli
                    - containerd.io
                  state: present

              - name: Vérification du service Docker
                service:
                  name: docker
                  state: started
                  enabled: true
        dest: "{{ project_path_expanded }}/ansible/playbooks/install_docker.yml"
        mode: '0644'

    # Lancer le playbook Docker après sa création
    - name: Lancer le playbook Docker pour installer Docker et Docker Compose
      command: ansible-playbook ansible/playbooks/install_docker.yml --ask-become-pass
      args:
        chdir: "{{ project_path_expanded }}"

    # Autres étapes (création de server.properties, etc.)...
    # Reste des étapes ici...
