---
- name: Création de l'arborescence et déploiement du serveur Minecraft
  hosts: localhost
  become: yes
  vars_prompt:
    - name: "server_ip"
      prompt: "Quelle adresse IP souhaitez-vous utiliser pour le fichier hosts ?"
      private: no
  tasks:
    # Création de l'arborescence
    - name: Cloner le dépôt Git
      git:
        repo: 'https://github.com/Vialle-Joris/SAE5.02.git'
        dest: '/root/test/SAE5.02'
        version: master
        force: yes

    - name: Création des répertoires pour Ansible, Docker et leur contenu
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - '/root/test/SAE5.02/ansible/playbooks'
        - '/root/test/SAE5.02/ansible/roles'
        - '/root/test/SAE5.02/ansible/inventory'
        - '/root/test/SAE5.02/docker/configs'
        - '/root/test/SAE5.02/docker/mods'
        - '/root/test/SAE5.02/docker/worlds'

    - name: Créer des fichiers README dans les répertoires
      copy:
        content: "# Documentation"
        dest: "{{ item }}"
        mode: '0644'
      with_items:
        - '/root/test/SAE5.02/ansible/playbooks/README.md'
        - '/root/test/SAE5.02/ansible/roles/README.md'
        - '/root/test/SAE5.02/ansible/inventory/README.md'
        - '/root/test/SAE5.02/docker/configs/README.md'
        - '/root/test/SAE5.02/docker/mods/README.md'
        - '/root/test/SAE5.02/docker/worlds/README.md'

    # Création du playbook d'installation Docker
    - name: Création du playbook d'installation de Docker
      copy:
        content: |
          ---
          - name: Installation de Docker et Docker Compose
            hosts: all
            become: yes
            tasks:
              - name: Mise à jour des paquets
                apt:
                  update_cache: yes

              - name: Installation des dépendances
                apt:
                  name:
                    - apt-transport-https
                    - ca-certificates
                    - curl
                    - software-properties-common
                  state: present

              - name: Ajout de la clé GPG Docker
                become: yes
                shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

              - name: Ajout du repository Docker
                apt_repository:
                  repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

              - name: Installation de Docker et Docker Compose
                apt:
                  name:
                    - docker-ce
                    - docker-ce-cli
                    - containerd.io
                  state: present

              - name: Vérification du service Docker
                service:
                  name: docker
                  state: started
                  enabled: true
        dest: '/root/test/SAE5.02/ansible/playbooks/install_docker.yml'
        mode: '0755'

    # Création du fichier d'inventaire pour Ansible
    - name: Création du fichier d'inventaire pour Ansible
      copy:
        content: |
          [serveur_ubuntu]
          {{ server_ip }} ansible_ssh_user=joris ansible_ssh_pass=Sterling7mc ansible_become_pass=Sterling7mc

          [minecraft_server]
          {{ server_ip }} ansible_ssh_user=joris ansible_ssh_pass=Sterling7mc ansible_become_pass=Sterling7mc
        dest: '/root/test/SAE5.02/ansible/inventory/hosts'
        mode: '0644'

    # Création du fichier docker-compose.yml
    - name: Création du fichier docker-compose.yml
      copy:
        content: |
          version: "3.8"
          services:
            minecraft:
              image: itzg/minecraft-server
              container_name: minecraft_server
              ports:
                - "25565:25565"
              environment:
                EULA: "TRUE"
                TYPE: "FORGE"
                VERSION: "1.20.1"
                FORGEVERSION: "47.3.12"
                DIFFICULTY: "normal"
                ONLINE_MODE: "FALSE"
              volumes:
                - ./configs:/data
                - ./mods:/mods
                - ./worlds:/world
              restart: unless-stopped
        dest: '/root/test/SAE5.02/docker/docker-compose.yml'
        mode: '0644'

    # Configuration du fichier server.properties
    - name: Création du fichier server.properties
      copy:
        content: |
          # Minecraft server properties
          # Updated for SAE5.02

          allow-flight=false
          allow-nether=true
          difficulty=normal
          enable-command-block=true
          gamemode=survival
          generate-structures=true
          level-name=SAE5.02
          max-players=20
          motd=Bienvenue sur le serveur SAE5.02 !\nRejoignez-nous pour une aventure unique.
          online-mode=false
          pvp=true
          server-port=25565
          view-distance=12
          simulation-distance=10
          spawn-animals=true
          spawn-monsters=true
          spawn-npcs=true
          enable-rcon=true
          rcon.password=19fe8672f3067dc8c29761b1
          rcon.port=25575
        dest: '/root/test/SAE5.02/docker/configs/server.properties'
        mode: '0644'

    # Lancement du serveur Docker
    - name: Lancer le serveur Minecraft avec Docker Compose
      command: docker-compose up -d
      args:
        chdir: /root/test/SAE5.02/docker

    # Déploiement des mods via Ansible
    - name: Déploiement des mods sur le serveur Minecraft
      copy:
        src: /root/test/SAE5.02/docker/mods/
        dest: /home/joris/minecraft-server/mods/
        owner: root
        group: root
        mode: '0755'
        remote_src: no

    - name: Redémarrer le serveur Minecraft Docker pour appliquer les mods
      command: docker restart minecraft_server
