---
- name: Déploiement complet d'un serveur Minecraft Forge
  hosts: localhost
  become: yes  # Utilisation de sudo pour exécuter les tâches avec les privilèges d'administrateur
  become_method: sudo  # Spécifie la méthode pour escalader les privilèges
  vars_prompt:
    # Demande à l'utilisateur l'adresse IP qu'il souhaite utiliser pour le fichier hosts
    - name: "server_ip"
      prompt: "Quelle adresse IP souhaitez-vous utiliser pour le fichier hosts ?"
      private: no  # Affiche la réponse en clair
    # Demande à l'utilisateur le chemin absolu de son répertoire SAE5.02
    - name: "project_path"
      prompt: "Chemin absolu où est situé votre répertoire SAE5.02 (se termine par /SAE5.02/) ?"
      private: no  # Affiche la réponse en clair
      default: "~/SAE5.02"  # Valeur par défaut si l'utilisateur ne répond pas

  tasks:
    # Normalisation du chemin du projet pour gérer le chemin utilisateur (~)
    - name: Expander le chemin utilisateur (~) dans project_path
      set_fact:
        project_path_expanded: "{{ project_path | expanduser }}"

    # Création des répertoires pour Ansible, Docker et leur contenu
    - name: Création des répertoires pour Ansible, Docker et leur contenu
      file:
        path: "{{ project_path_expanded }}/{{ item }}"
        state: directory  # Crée le répertoire
        mode: '0755'  # Permet la lecture, écriture et exécution pour le propriétaire, lecture et exécution pour les autres
      with_items:
        - 'ansible/playbooks'
        - 'ansible/roles'
        - 'ansible/inventory'
        - 'docker/configs'
        - 'docker/mods'
        - 'docker/worlds'

    # Création de fichiers README dans les répertoires créés pour la documentation
    - name: Créer des fichiers README dans les répertoires
      copy:
        content: "# Documentation"  # Contenu du fichier README
        dest: "{{ project_path_expanded }}/{{ item }}"  # Destination des fichiers README
        mode: '0644'  # Lecture et écriture pour le propriétaire, lecture pour les autres
      with_items:
        - 'ansible/playbooks/README.md'
        - 'ansible/roles/README.md'
        - 'ansible/inventory/README.md'
        - 'docker/configs/README.md'
        - 'docker/mods/README.md'
        - 'docker/worlds/README.md'

    # Création du fichier d'inventaire Ansible
    - name: Création du fichier d'inventaire pour Ansible
      copy:
        content: |
          [serveur_ubuntu]
          {{ server_ip }} ansible_ssh_user=joris ansible_ssh_pass=Sterling7mc ansible_become_pass=Sterling7mc

          [minecraft_server]
          {{ server_ip }} ansible_ssh_user=joris ansible_ssh_pass=Sterling7mc ansible_become_pass=Sterling7mc
        dest: "{{ project_path_expanded }}/ansible/inventory/hosts"  # Chemin de destination du fichier hosts
        mode: '0644'  # Lecture et écriture pour le propriétaire, lecture pour les autres

    # Création du fichier server.properties pour configurer les paramètres du serveur Minecraft
    - name: Création du fichier server.properties
      copy:
        content: |
          # Minecraft server properties
          # Updated for SAE5.02

          allow-flight=false
          allow-nether=true
          difficulty=normal
          enable-command-block=true
          gamemode=survival
          generate-structures=true
          level-name=SAE5.02
          max-players=20
          motd=Bienvenue sur le serveur SAE5.02 !\nRejoignez-nous pour une aventure unique.
          online-mode=false
          pvp=true
          server-port=25565
          view-distance=12
          simulation-distance=10
          spawn-animals=true
          spawn-monsters=true
          spawn-npcs=true
          enable-rcon=true
          rcon.password=19fe8672f3067dc8c29761b1
          rcon.port=25575
        dest: "{{ project_path_expanded }}/docker/configs/server.properties"  # Chemin de destination du fichier server.properties
        mode: '0644'  # Lecture et écriture pour le propriétaire, lecture pour les autres

    # Déplacement des fichiers .jar (mods) depuis le répertoire SAE5.02 vers le répertoire mods de Docker
    - name: Déplacer les fichiers .jar vers le répertoire des mods
      shell: mv {{ project_path_expanded }}/*.jar {{ project_path_expanded }}/docker/mods/  # Déplacement des fichiers .jar
      args:
        removes: "{{ project_path_expanded }}/*.jar"  # Assure que les fichiers .jar sont déplacés et non copiés

    # Création du fichier docker-compose.yml pour configurer et lancer le serveur Docker Minecraft
    - name: Création du fichier docker-compose.yml
      copy:
        content: |
          version: "3.8"
          services:
            minecraft:
              image: itzg/minecraft-server
              container_name: minecraft_server
              ports:
                - "25565:25565"
              environment:
                EULA: "TRUE"
                TYPE: "FORGE"
                VERSION: "1.20.1"
                FORGEVERSION: "47.3.12"
                DIFFICULTY: "normal"
                ONLINE_MODE: "FALSE"
              volumes:
                - ./configs:/data
                - ./mods:/mods
                - ./worlds:/world
              restart: unless-stopped
        dest: "{{ project_path_expanded }}/docker/docker-compose.yml"  # Chemin du fichier docker-compose.yml
        mode: '0644'  # Lecture et écriture pour le propriétaire, lecture pour les autres

    # Lancement du serveur Minecraft avec Docker Compose
    - name: Lancer le serveur Minecraft avec Docker Compose
      command: docker-compose up -d  # Lance le serveur en mode détaché
      args:
        chdir: "{{ project_path_expanded }}/docker"  # Change de répertoire pour exécuter la commande dans le bon répertoire

    # Déploiement des mods sur le serveur Minecraft
    - name: Déploiement des mods sur le serveur Minecraft
      copy:
        src: "{{ project_path_expanded }}/docker/mods/"  # Source des fichiers mods
        dest: "/home/joris/minecraft-server/mods/"  # Destination des fichiers mods dans le conteneur Docker
        owner: root  # Propriétaire des fichiers sur le conteneur
        group: root  # Groupe des fichiers sur le conteneur
        mode: '0755'  # Permissions des fichiers
        remote_src: no  # Indique que la source est sur la machine locale et non sur le conteneur distant

    # Redémarrage du serveur Minecraft pour appliquer les mods
    - name: Redémarrer le serveur Minecraft Docker pour appliquer les mods
      command: docker restart minecraft_server  # Redémarre le conteneur Minecraft pour appliquer les mods
